---
version: 2.1

# Make sure to enable Project Settings > Advanced > Dynamic Configuration
# in the CircleCI UI so that this option will work.
setup: true

orbs:
  golden: evil-org/golden@1

workflows:
  fastapi_k8s:
    jobs:
      - golden/unit_tests
      - golden/build
